#!/bin/bash
#
# Release one or more RPM packages to the Yum repository.
# v3.2 20150310, jorge (at) morgado (dot) ch
#
# Usage:
#
#   release-rhel /path/to/rpm/files [distro] [version]
#
#   distro    Distribution name (default: rhel)
#   version   Distribution version (default: 7)

BASEDIR="/path/to/your/yum/repository"

# temporary directory holding RPM packages
TMPDIR="${1}"

# -----------------------------------------------------------------------------
# DO NOT CHANGE ANYTHING BELOW THIS LINE UNLESS YOU KNOW WHAT YOU ARE DOING

# assume rhel-7 if not provided
DISTRO=${2-rhel}
VERSION=${3-7}

function _usage()
{
    echo
    echo "Usage: ${0} /path/to/rpm/files [distro] [version]"
    echo
    echo "  distro    Distribution name (default: rhel)"
    echo "  version   Distribution version (default: 6)"
    echo
}

function _fatal()
{
    echo "Error: ${1}."
    _usage
    exit 1
}

function _release()
{
    local FILE="${1}"
    local TYPE="${2}"

    # Create the target directory if not yet exisiting
    [ -d "${REPOBASE}/${TYPE}" ] || \
      mkdir "${REPOBASE}/${TYPE}"

    if ( cp ${FILE} ${REPOBASE}/${TYPE} ) && \
       ( chown -R root:root ${REPOBASE} ); then
        if ( createrepo ${REPOBASE}/${TYPE} ) && \
           ( chmod -R o-w+r ${REPOBASE} ); then
            echo "${FILE} released."
        else
            _fatal "Failed to createrepo (${REPOBASE}/${TYPE})"
        fi
    else
        _fatal "Failed to move RPM to repostory"
    fi
}

REPOBASE="${BASEDIR}/${DISTRO}/${VERSION}"

# Show usage information
case "${1}" in
  -h|--help*)
    _usage
    exit 2
    ;;
esac

[ -d "${TMPDIR}" ] || _fatal "RPM temp directory not found (${TMPDIR})"
[ -d "${REPOBASE}" ] || _fatal "Repo's base directory not found (${REPOBASE})"

for RPMFILE in `find ${TMPDIR} -name "*.rpm"`; do
    # extract extension from file name
    RPMFILE="${RPMFILE%*.rpm}"

    # read architecture
    ARCH="${RPMFILE##*.}"

    case "${ARCH}" in
    "src")
        _release "${RPMFILE}.rpm" "SRPMS"
        ;;
    "noarch")
        _release "${RPMFILE}.rpm" "x86_64"
        _release "${RPMFILE}.rpm" "i386"
        ;;
    "x86_64")
        _release "${RPMFILE}.rpm" "x86_64"
        ;;
    "i386")
        _release "${RPMFILE}.rpm" "i386"
        ;;
    *)
        _fatal "Unknown RPM type (${ARCH})"
    esac
done

rm -rf "${TMPDIR}"

exit 0
